### ISSUE TITLE
Not able to add this library to project

### ISSUE THREAD

**Issue by anilreddy-insert** [tehras/charts#23]
I have been trying to add this library to my project and getting below error at the time of syncing the library. My project's Compose version is 1.0.0 and tehra's charts version used in my project is alpha-0.12.0

org.gradle.internal.resolve.ModuleVersionNotFoundException: Cannot resolve external dependency org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.5.10 because no repositories are defined.

**Comment by GabrielGircenko** [comment]
@anilreddy-insert please check the latest README
