### ISSUE TITLE
compose chart for desktop in intelliJ IDEA

### ISSUE THREAD

**Issue by momeni1367** [tehras/charts#29]
Please help me for add implementation for compose chart desktop in my project intelliJ.
I want to add charts(bar & pie) to compose desktop project.

**Comment by bytebeats** [comment]
@momeni1367 this is supporting [desktop](https://github.com/bytebeats/compose-charts-desktop)

**Comment by gulabsagevadiya** [comment]
Hey @momeni1367, Can you please help me with how to add this lib in compose desktop?
